# Generated by Django 4.2.21 on 2025-05-23 09:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_galleryitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
