# Generated by Django 4.2.21 on 2025-05-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'verbose_name': 'Елемент галереї', 'verbose_name_plural': 'Галерея'},
        ),
    ]
